[build-system]
requires = ["setuptools", "pybind11==2.11.1", "setuptools_scm==7.1.0"]

[tool.cibuildwheel]
build-frontend = "build"
before-all = "manylinux/before_all.sh {package}"
before-build = "manylinux/before_build.sh"
manylinux-x86_64-image="manylinux2014"
manylinux-i686-image="manylinux2014"
manylinux-aarch64-image="manylinux2014"
build = ["cp38-manylinux*", "cp39-manylinux*", "cp310-manylinux*", "cp311-manylinux*", "cp312-manylinux*"]

before-test = "pip install -r {package}/requirements.txt -r {package}/requirements-3.12.txt"
test-command = "pytest -v {package}/tests"

[tool.cibuildwheel.linux]
archs = ["x86_64"]

[tool.cibuildwheel.linux.environment]
CC = "ccache gcc"
CFLAGS = "-flto"
LDFLAGS = "-flto"

[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 100
py_version = 38

[tool.black]
line-length = 100
target-versions = ["py38", "py39", "py310", "py311", "py312"]
